### ISSUE TITLE
Repeats in plugins? 

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick#32]
https://github.com/ImageProcessing-ElectronicPublications/photoquick/blob/ccae4eeb9c2da025e3f5d4a9f6246c294412cbff/src/main.cpp#L627-L709
Repeats in plugins:
* https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/tree/master/src/transform/geoconformal
* https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/tree/master/src/transform/deskew
and partly in https://github.com/ImageProcessing-ElectronicPublications/photoquick/blob/master/src/transform.cpp

Can I use bicubic interpolation from https://github.com/ImageProcessing-ElectronicPublications/photoquick/blob/master/src/main.cpp instead of duplicating code?

**Comment by ksharindam** [comment]
That is the problem of using single executable. 
As the plugins are not linked with the main program, they can not call any function in main program directly.
That's why in most plugins, i have copied code from filters.cpp.

But there is a dirty work around. that is declare the function in Window as a SLOT.
Then in the plugin create a SIGNAL, and connect that signal and slot. then emit signal.
The slot must return void.

**Comment by zvezdochiot** [comment]
@ksharindam say:
>The slot must return void.

Not. It won't do.
